Storybook auth
r-aritra/outdoor-event-fe pull request #15
Opened 2023-12-29 11:18 UTC by rutvik-balar

**Task**
Add Stories into log-in and sign-in page 

**Todo**
write stories into log in 
write stories into my sign-in screen 

**How to check**
  yarn dev
  yarn storybook 
 
**Evidences**
<img width="923" alt="Screenshot 2023-12-29 at 4 46 19 PM" src="https://github.com/r-aritra/outdoor-event-fe/assets/76244286/f98fcf41-277d-49b3-b32d-05a6b5139ee7">
<img width="966" alt="Screenshot 2023-12-29 at 4 46 29 PM" src="https://github.com/r-aritra/outdoor-event-fe/assets/76244286/a3c8bd45-ffaf-4b6c-815a-e9ba55d8ccf8">
<img width="930" alt="Screenshot 2023-12-29 at 4 46 49 PM" src="https://github.com/r-aritra/outdoor-event-fe/assets/76244286/3354a991-a90e-41b5-8c08-9adb9817e717">
<img width="932" alt="Screenshot 2023-12-29 at 4 46 59 PM" src="https://github.com/r-aritra/outdoor-event-fe/assets/76244286/db732449-9eb3-414e-9702-8fd00738672a">

**build**
**Related Links**

2024-01-03 06:36 UTC, r-aritra commented
pull from main to align with latest main branch

2024-01-03 06:42 UTC, r-aritra requested changes
Please remove unwanted changes from the PR

2024-01-03 06:42 UTC, r-aritra commented on vite.config.mts
> -// https://vitejs.dev/config/
do not remove auto generated comments

2024-01-03 10:30 UTC, rutvik-balar commented on vite.config.mts
> -// https://vitejs.dev/config/
resolved

2024-01-09 05:13 UTC, r-aritra approved these changes
lgtm

2024-01-09 05:13 UTC, merged