I18n login
r-aritra/outdoor-event-fe pull request #17
Opened 2024-01-02 04:44 UTC by rutvik-balar

**Task**
I18 in auth
 
**Todo**
 
add i18n into login
add i18n into register 
 
**How to check**
npm run dev

**Evidences**
 
<img width="423" alt="Screenshot 2024-01-02 at 10 13 12 AM" src="https://github.com/r-aritra/outdoor-event-fe/assets/76244286/7227dc49-7d66-4b57-a70c-4d4953751ba2">
<img width="428" alt="Screenshot 2024-01-02 at 10 13 54 AM" src="https://github.com/r-aritra/outdoor-event-fe/assets/76244286/14cf6c98-ad42-4dda-958a-224280a09d9d">

 
**build**
**Related Links**

2024-01-03 06:33 UTC, r-aritra requested changes

2024-01-03 06:33 UTC, r-aritra commented on src/config/translations/locales/en.ts
> +  page: {
make the features as keys

2024-01-03 06:33 UTC, r-aritra commented on src/features/Login/Login.tsx
> +              error={form.errors.email && t('page.login.page.login.invalidEmailError')}
wrong i18n string

2024-01-03 06:34 UTC, r-aritra commented
Try to add eslint rules for correct i18n string

2024-01-03 08:49 UTC, rutvik-balar commented on src/config/translations/locales/en.ts
> +  page: {
resolved

2024-01-03 08:49 UTC, rutvik-balar commented on src/features/Login/Login.tsx
> +              error={form.errors.email && t('page.login.page.login.invalidEmailError')}
resolved

2024-01-05 04:36 UTC, r-aritra approved these changes
lgtm

2024-01-05 04:36 UTC, merged