Auth api call
r-aritra/outdoor-event-fe pull request #18
Opened 2024-01-03 04:42 UTC by rutvik-balar

**Task**
Auth api call
 
**Todo**
 
add api call of login API 
add api call of register and valid otp send otp api in register screen
 
**How to check**
npm run dev

**Evidences**
 
[screen-capture (1).webm](https://github.com/r-aritra/outdoor-event-fe/assets/76244286/ba5b4e81-63d4-4f72-bd5b-6bd9788e6976)

 
**build**
**Related Links**

2024-01-03 06:30 UTC, r-aritra requested changes

2024-01-03 06:30 UTC, r-aritra commented on src/features/Login/Login.tsx
>      validate: {
use zod for validation schema

2024-01-03 06:30 UTC, r-aritra commented on src/features/Login/Login.tsx
> +  };
Move to utils module
add styles for
Success: color= green, icon = tick
Error: color = red, icon = cross/x
Info: color = blue icon = info
Should be able to close the notification

2024-01-03 06:30 UTC, r-aritra commented on src/features/Login/Login.tsx
>    const handleSubmit = async () => {
remove async not required

2024-01-03 06:30 UTC, r-aritra commented on src/features/Login/Login.tsx
>      console.log(data);
remove logs

2024-01-03 06:30 UTC, r-aritra commented on src/features/Login/Login.tsx
> +        data: { ...data, device_id: '1234321', device_type: 'web' },
check if device_id, device_type can be filled dynamically

2024-01-03 06:30 UTC, r-aritra commented on src/features/Login/Login.tsx
> +          navigate('/');
store token on login success

2024-01-03 06:30 UTC, r-aritra commented on src/test/mocks/browser.ts
> +  http.post('*/v1/api/register-user', async () => {
check if rest is replaced with http for msw

2024-01-03 06:30 UTC, r-aritra commented on src/features/Login/Login.tsx
> -      />
integrate loader
Check how to integrate loader globally, as fallback using Suspense

2024-01-03 06:30 UTC, r-aritra commented on src/features/Signup/Signup.tsx
> +  };
same as comment in Login component

2024-01-03 06:30 UTC, r-aritra commented on src/features/Signup/Signup.tsx
> -      />
integrate loader

2024-01-03 09:45 UTC, rutvik-balar commented on src/features/Login/Login.tsx
>    const handleSubmit = async () => {
resolved

2024-01-03 09:46 UTC, rutvik-balar commented on src/features/Login/Login.tsx
>      console.log(data);
resolved

2024-01-03 09:53 UTC, rutvik-balar commented on src/features/Login/Login.tsx
> +        data: { ...data, device_id: '1234321', device_type: 'web' },
resolved

2024-01-03 09:56 UTC, rutvik-balar commented on src/features/Signup/Signup.tsx
> +  };
resolved

2024-01-03 09:56 UTC, rutvik-balar commented on src/features/Signup/Signup.tsx
> -      />
resolved

2024-01-03 10:54 UTC, rutvik-balar commented on src/test/mocks/browser.ts
> +  http.post('*/v1/api/register-user', async () => {
resolved

2024-01-05 05:04 UTC, r-aritra approved these changes
lgtm

2024-01-05 05:05 UTC, merged